server:
  port: 1200
spring:
  redis:
    database: 0
    host: 192.168.195.129
    port: 6379
    password: 000000
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
        min-idle: 0
    timeout: 0
  rabbitmq:
    host: 192.168.195.129
    port: 5675
    username: guest
    password: guest
    virtual-host: /
